<?php

/**
 * @file
 * The module file with theming functions.
 */

/**
 * Implements hook_theme().
 */
function ec_shortcodes_theme($existing, $type, $theme, $path) {
  return [
    'ec_shortcodes_button' => [
      'variables' => [
         'url' => NULL,
         'text' => NULL,
      ],
    ],
    'ec_shortcodes_accordion' => [
      'variables' => [
         'kicker' => NULL,
         'title' => NULL,
         'icon' => NULL,
      ],
    ],
    'ec_shortcodes_author_bio' => [
      'variables' => [
         'name' => NULL,
         'bio' => NULL,
      ],
    ],
  ];
}

