<?php

/**
 * @file
 * The module file with theming functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_form_alter().
 */
function ec_shortcodes_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if ($form_id === 'embedded_content_dialog_form' &&  isset($form['config']['plugin_id'])) {
    // Alphabetically sort the options for embedded content.
    uasort(
      $form['config']['plugin_id']['#options'],
      function (TranslatableMarkup $a, TranslatableMarkup $b) {
        return (string) $a <=> (string) $b;
      }
    );
  }
}

/**
 * Implements hook_theme().
 */
function ec_shortcodes_theme($existing, $type, $theme, $path) {
  return [
    'ec_shortcodes_accordion' => [
      'variables' => [
        'kicker' => NULL,
        'accordion_title' => NULL,
        'icon' => NULL,
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_card_policy' => [
      'variables' => [
        'kicker' => NULL,
        'card_title' => NULL,
        'url' => NULL,
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_card_prompt' => [
      'variables' => [
        'intro' => NULL,
        'prompt' => NULL,
        'text' => NULL,
        'url' => NULL,
      ],
    ],
    'ec_shortcodes_card_quote' => [
      'variables' => [
        'dark' => NULL,
        'text' => NULL,
        'cite' => NULL,
      ],
    ],
    'ec_shortcodes_do_dont_table' => [
      'variables' => [
        'caption' => NULL,
        'rows' => NULL,
      ],
    ],
    'ec_shortcodes_featured_resource_ext' => [
      'variables' => [
        'kicker' => NULL,
        'url' => NULL,
        'title' => NULL,
        'summary' => NULL,
      ],
    ],
    'ec_shortcodes_featured_resource' => [
      'variables' => [
        'content_reference' => NULL,
        'kicker' => NULL,
      ],
    ],
    'ec_shortcodes_note' => [
      'variables' => [
        'heading' => NULL,
        'type' => NULL,
        'text' => NULL,
        'text_override' => NULL,
      ],
    ],

    'ec_shortcodes_note_join' => [
      'variables' => [
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_note_disclaimer' => [
      'variables' => [
        'heading' => NULL,
      ],
    ],
    'ec_shortcodes_ring' => [
      'variables' => [
        'heading' => NULL,
        'text' => NULL,
      ],
    ],
  ];
}
