<?php

/**
 * @file
 * The module file with theming functions.
 */

/**
 * Implements hook_theme().
 */
function ec_shortcodes_theme($existing, $type, $theme, $path) {
  return [
    'ec_shortcodes_button' => [
      'variables' => [
        'url' => NULL,
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_accordion' => [
      'variables' => [
        'kicker' => NULL,
        'title' => NULL,
        'icon' => NULL,
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_card_policy' => [
      'variables' => [
        'kicker' => NULL,
        'title' => NULL,
        'src' => NULL,
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_card_prompt' => [
      'variables' => [
        'intro' => NULL,
        'prompt' => NULL,
        'text' => NULL,
        'url' => NULL,
      ],
    ],
    'ec_shortcodes_card_quote' => [
      'variables' => [
        'text' => NULL,
        'cite' => NULL,
      ],
    ],
    'ec_shortcodes_checklist' => [
      'variables' => [
        'checklist' => NULL,
      ],
    ],
    'ec_shortcodes_do_dont_table' => [
      'variables' => [
        'caption' => NULL,
        'rows' => NULL,
      ],
    ],
    'ec_shortcodes_featured_resource_ext' => [
      'variables' => [
        'kicker' => NULL,
        'url' => NULL,
        'title' => NULL,
        'summary' => NULL,
      ],
    ],
    'ec_shortcodes_featured_resource' => [
      'variables' => [
        'content_reference' => NULL,
      ],
    ],
    'ec_shortcodes_note' => [
      'variables' => [
        'heading' => NULL,
        'type' => NULL,
        'text' => NULL,
        'text_override' => NULL,
      ],
    ],

    'ec_shortcodes_note_join' => [
      'variables' => [
        'text' => NULL,
      ],
    ],
    'ec_shortcodes_note_disclaimer' => [
      'variables' => [
        'heading' => NULL,
      ],
    ],
    'ec_shortcodes_note_ring' => [
      'variables' => [
        'heading' => NULL,
        'text' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ec_shortcodes_preprocess(&$variables, $hook) {
  if (in_array($hook, ['ec_shortcodes_accordion', 'ec_shortcodes_card_policy', 'ec_shortcodes_card_prompt',
    'ec_shortcodes_note', 'ec_shortcodes_do_dont_table', 'ec_shortcodes_note_join', 'ec_shortcodes_note_disclaimer',
  ])) {
    $variables['theme_path'] = \Drupal::theme()->getActiveTheme()->getPath();
  }
}
